<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFrameworks>net9.0-windows;net8.0-windows;net48</TargetFrameworks>
		<UseWindowsForms>true</UseWindowsForms>
		<IsPackable>true</IsPackable>
		<Authors>Lior Banai</Authors>
		<Company>Analogy.LogViewer</Company>
		<RepositoryUrl>https://github.com/Analogy-LogViewer/Real-Time-Log-Server</RepositoryUrl>
		<PackageProjectUrl>https://github.com/Analogy-LogViewer/Real-Time-Log-Server</PackageProjectUrl>
		<Version>0.0.3</Version>
		<Copyright>Lior Banai @ 2020-2024</Copyright>
		<PackageIcon>Analogy.gRPC.service.png</PackageIcon>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Analogy.LogViewer.Interfaces" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="System.Resources.Extensions" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\Assets\Analogy.gRPC.service.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Update="Microsoft.SourceLink.GitHub" />
	</ItemGroup>
	<!-- Analyzers (Roslyn, Meziantou, StyleCop, ...) -->
	<ItemGroup>
		<PackageReference Include="Meziantou.Analyzer">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Roslynator.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="StyleCop.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup Condition=" '$(TargetFramework)' == 'net48' ">
		<PackageReference Include="Microsoft.Bcl.HashCode" />
		<PackageReference Include="Meziantou.Polyfill">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>